// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bridal_cta: dynamic(() => import("./BridalCta")),
  bridal_package: dynamic(() => import("./BridalPackage")),
  contact: dynamic(() => import("./Contact")),
  hero_three_image: dynamic(() => import("./HeroThreeImage")),
  homepage_hero: dynamic(() => import("./HeroLargeImageWithLinks")),
  info3_col: dynamic(() => import("./Info3Col")),
  info4_col: dynamic(() => import("./Info4Col")),
  info_list_wide_image: dynamic(() => import("./InfoListWideImage")),
  information_panel: dynamic(() => import("./InformationPanel")),
  main_services: dynamic(() => import("./MainServices")),
  paragraph_image_overlap: dynamic(() => import("./ParagraphImageOverlap")),
  service_body: dynamic(() => import("./ServiceBody")),
  services_hero: dynamic(() => import("./ServicesHero")),
  simple_heading_with_background_image: dynamic(
    () => import("./SimpleHeadingWithBackgroundImage"),
  ),
  simple_hero: dynamic(() => import("./SimpleHero")),
  single_column: dynamic(() => import("./SingleColumn")),
  testimonials: dynamic(() => import("./Testimonials")),
  timeline: dynamic(() => import("./Timeline")),
  timeline_large: dynamic(() => import("./TimelineLarge")),
  training_body: dynamic(() => import("./TrainingBody")),
  tryptich: dynamic(() => import("./Tryptich")),
};
